---
title: "Teaching"
title-block-style: none
toc: false
---
:::: {.academic-shell}
::: {.academic-sidebar}
{{< include _profile.qmd >}}
:::

::: {.academic-main}

## Doctoral

### ALERT Geomaterials Olek Zienkiewicz School on Constitutive Modelling of Geomaterials | 2025
- *Introduction to Machine Learning* and *Constitutive modelling meets Machine Learning*.
- Material: [programme](https://soilmodels.com/alert-oz-school-2025/) and [code and exercises](https://github.com/filippo-masi/ALERT-OlekZienkiewicz-ML).


### ALERT Geomaterials Doctoral School on Machine Learning in Geomechanics | 2023
- *Introduction to Regression Methods* and *Physics-Informed and Thermodynamics-Based Neural Networks*.
- Material: [course book](http://www.alertgeomaterials.eu/data/school/2023/2023_ALERT_school.pdf) and [slides/code and exercises](https://github.com/alert-geomaterials/2023-doctoral-school).

### Computational Structural Mechanics Association Junior Workshop | 2022
- *Deep learning, simulation temps réel et réduction de modèles*.
- Material: [website](https://csma.asso.univ-lorraine.fr/csma-juniors/) and [code and exercises](https://github.com/filippo-masi/CSMA-Workshop-in-Deep-Learning).

---

## Master and bachelor

### Univ. Grenoble Alpes (UGA)

- *Machine learning for Physics* (2026-.) · Master (MSIAM/ENSIMAG) · Course coordinator and lecturer
- *Machine learning for Mechanics* (2026-.) · Master (MGCER) · Course coordinator and lecturer
- *Introduction to﻿﻿﻿‌ numerical methods* (2025) · Bachelor (L3M/L3MAA) · Lecturer

### École Centrale de Nantes (ECN)

- *Experimental imaging analysis for engineers* (2020–2023) · Master · Course coordinator and lecturer
- *Continuum mechanics* (2021–2022) · Bachelor · Lecturer

### École nationale des ponts et chaussées (ENPC)

- *Advanced computational mechanics* (2018–2019) · Master · Lecturer
- *Computational mechanics* (2018–2019) · Bachelor · Lecturer


:::
::::
